apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-password
      key: redis-password
  - name: allowedTopics
    value: "A,C"
  - name: publishingScopes
    value: "react-form=A,C;python-subscriber=;java-subscriber="
  - name: subscriptionScopes
    value: "python-subscriber=A;java-subscriber=C"
auth:
  secretStore: kubernetes
