apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-subscriber
  namespace: dapr-cross-cloud
  labels:
    app: python-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-subscriber
  template:
    metadata:
      labels:
        app: python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-subscriber"
        dapr.io/app-port: "5001"
    spec:
      containers:
      - name: python-subscriber
        image:  europe-west1-docker.pkg.dev/prj-dataplane-n-demo-30534/kubecon-demo-registry/python-subscriber:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always